let okvir=document.getElementById("okvir");
iscrtajRaspored(okvir,["Ponedjeljak","Utorak","Srijeda","Četvrtak","Petak"],9,21);
dodajAktivnost(okvir,"WT","predavanje",9,12,"Ponedjeljak");
dodajAktivnost(okvir,"WT","vježbe",12,13.5,"Ponedjeljak");
dodajAktivnost(okvir,"RMA","predavanje",14,17,"Ponedjeljak");
dodajAktivnost(okvir,"RMA","vježbe",12.5,14,"Utorak");
dodajAktivnost(okvir,"DM","tutorijal",14,16,"Utorak");
dodajAktivnost(okvir,"DM","predavanje",16,19,"Utorak");
dodajAktivnost(okvir,"PJP","vježbe",12,13,"Petak");
dodajAktivnost(okvir,"PJP","predavanje",9,12,"Petak");
dodajAktivnost(okvir,"RG","predavanje",9,12,"Četvrtak");

let okvir2=document.getElementById("okvir2");
iscrtajRaspored(okvir2,["Ponedjeljak","Utorak","Srijeda","Četvrtak","Petak"],9,21);
dodajAktivnost(okvir2,"WT","predavanje",9,12,"Srijeda");
dodajAktivnost(okvir2,"WT","vježbe",19,20.5,"Ponedjeljak");
dodajAktivnost(okvir2,"VVS","vježbe",10.5,12,"Utorak");
dodajAktivnost(okvir2,"OOI","predavanje",12,15,"Utorak");
dodajAktivnost(okvir2,"OIS","predavanje",15,18,"Utorak");
dodajAktivnost(okvir2,"RG","vježbe",12,14,"Srijeda");
dodajAktivnost(okvir2,"OOI","vježbe",15,16,"Srijeda");
dodajAktivnost(okvir2,"PJP","vježbe",12,13,"Petak");
dodajAktivnost(okvir2,"PJP","predavanje",9,12,"Petak");
dodajAktivnost(okvir2,"RG","predavanje",9,11,"Četvrtak");
dodajAktivnost(okvir2,"RG","tutorijal",11,12,"Četvrtak");
dodajAktivnost(okvir2,"VVS","predavanje",12,15,"Četvrtak");